version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - db:db
    volumes:
      - web-django:/app
      - web-static:/app/static
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn rushing.wsgi:application -w 2 -b :8000

  nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - web-static:/www/static
      links:
        - web:web

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata: