version: "3.9"
   
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    restart: always
    build:
      context: ./web
      args:
        - SECRET_KEY=$SECRET_KEY
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASS=$DB_PASS
        - DB_SERVER=$DB_SERVICE
        - DB_PORT=$DB_PORT
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      # - web-django:/app
      - web-static:/app/static
    env_file: .env
    environment:
      DEBUG: 'true'
    command: /usr/local/bin/gunicorn rushing.wsgi:application -w 2 -b :8000

  nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - web-static:/www/static
      links:
        - web:web

volumes:
  # web-django:
  web-static:
  pgdata: